# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate `client`

on:
  push:
    branches:
      - master
      - qa
      - dev
  pull_request:
    branches:
      - master
      - qa
      - dev

defaults:
  run:
    working-directory: client

jobs:
  validate-client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install -g yarn
      - name: Run yarn
        run: |
          yarn install
          yarn workspace maslow-access run build
          yarn workspace maslow-author run build
          yarn workspaces run test:cov
          yarn workspaces run lint
      - if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./client/access/coverage/lcov.info
      - if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./client/author/coverage/lcov.info
      - if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./client/shared/coverage/lcov.info
